---
title: "Homework 6"
author: "Joshua Carpenter"
date: "2023-11-28"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggfortify)
```
 
## Problem 2
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```
 
```{r}
weather_boot_df <- weather_df %>%
  modelr::bootstrap(n = 5000) %>%
  mutate(models = map(strap, \(df) lm(tmax ~ tmin + prcp, data = df)),
         r_squared = map(models, \(model) summary(model)$r.squared) %>% unlist(),
         coeffs = map(models, coefficients)) %>%
  unnest_wider(coeffs) %>%
  mutate(log_prod = log(ifelse(tmin * prcp > 0, tmin * prcp, NA))) %>%
  select(.id, r_squared, log_prod)

ggplot(data = weather_boot_df, mapping = aes(x = r_squared)) +
  geom_histogram()

ggplot(data = weather_boot_df, mapping = aes(x = log_prod)) +
  geom_histogram(na.rm = TRUE)

quantile(weather_boot_df$r_squared, c(0.025, 0.975))
quantile(weather_boot_df$log_prod, c(0.025, 0.975), na.rm = TRUE)
```
 
 ## Problem 2
```{r}
birthweight <- read_csv("Data/birthweight.csv") %>%
  mutate(
    babysex = factor(babysex, levels = 1:2, labels = c("male", "female")),
    frace = factor(frace, levels = c(1, 2, 3, 4, 8, 9), labels = c("White", "Black", "Asian", "Puerto Rican", "Other", "Unknown")),
    mrace = factor(mrace, levels = c(1, 2, 3, 4, 8), labels = c("White", "Black", "Asian", "Puerto Rican", "Other")),
    malform = factor(malform, levels = 0:1, labels = c("absent", "present"))
  )
```

I picked a few variables that seemed likely to be predictive of birthweight and looked to be correlated to birthweight based on a scatterplot.
```{r}
bwt_model <- 
  lm(bwt ~ blength + babysex + bhead + gaweeks + pnumsga + wtgain, 
     data = birthweight)
autoplot(bwt_model, which = 1, ncol = 1) +
    ggplot2::theme_minimal() +
    ggplot2::theme(aspect.ratio = 1)
```
 
 